[package]
name = "tisu-fs"
version = "0.1.0"
authors = ["1363558876@qq.com <1363558876@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tisu-memory = { path = "../../github/tisu-memory" }
tisu-sync = { path = "../../github/tisu-sync" }
tisu-driver = { path = "../../github/tisu-driver" }
device-buffer = { path = "../../github/device-buffer" }
